name: cogniosis
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  flutter_screenutil: ^5.9.1
  syncfusion_flutter_charts: ^25.2.5
  dotted_border: ^2.1.0
  flutter_inner_shadow: ^0.0.1
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1

  intl: ^0.19.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.3
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.1.2
  image: ^4.2.0
  tflite_flutter: ^0.10.4
  url_launcher: ^6.3.0
  loading_animation_widget: ^1.2.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/logo/
     - assets/home/
     - assets/results/
     - assets/model/
     - assets/
